name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: A long process
    runs-on: ubuntu-latest

    steps:
      - name: A 1 minutes process
        run: |
          sleep 1m
          mkdir releases
          echo 'first' > releases/first.txt
          echo 'second' > releases/second.txt
          echo 'third' > releases/third.txt
          echo 'forth' > releases/forth.txt

      - uses: actions/upload-artifact@v7
        with:
          name: release-archives
          overwrite: true
          path: releases/*.txt
