name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: A long process
    runs-on: ubuntu-latest

    steps:
      - name: A 30 seconds process
        run: |
          sleep 30s
          mkdir releases
          echo 'first' > releases/first.txt
          echo 'second' > releases/second.txt
          echo 'third' > releases/third.txt

      - uses: actions/upload-artifact@v7
        with:
          name: release-archives
          overwrite: true
          path: releases/*.txt

  update-releases:
    name: Update release assets
    needs: build
    if: |-
      github.event_name == 'push' &&
      startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: release-archives
          path: releases

      - name: Update release assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
          LATEST_COMMIT: ${{ github.event.head_commit.message }}
        run: |
          RELEASE_VERSION=$(echo "$LATEST_COMMIT" | head -n 1 | sed 's/chore(release): /v/')

          shopt -s nullglob

          for to_upload in releases/*.txt; do
            gh release upload "$RELEASE_VERSION" "${to_upload}" --clobber
          done
