name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  xyz-publish:
    name: Publish
    uses: projek-xyz/actions/.github/workflows/release.yml@release-assets

    permissions:
      contents: write

  update-assets:
    name: Upload assets
    needs: xyz-publish
    if: |-
      needs.xyz-publish.outputs.should-upload == '1' &&
      startsWith(github.event.head_commit.message, 'chore(release):')
    uses: projek-xyz/actions/.github/workflows/uploads.yml@release-assets
    with:
      workflow_name: CI

    permissions:
      contents: write

  self-publish:
    name: Publish binaries
    if: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        mkdir releases
        echo 'first' > releases/first.txt
        echo 'second' > releases/second.txt
        npx @feryardiant/read-changelog > PUBLISH.txt

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: releases/*.txt
        body_path: PUBLISH.txt
